services:
  - type: web
    name: salespredict-api
    runtime: python
    region: frankfurt
    plan: free
    rootDir: backend
    pythonVersion: 3.11.9 
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
